services:
  university.db:
    container_name: University.Database
    image: "postgres:latest"
    environment:
      - ACCEPT_EULA=y
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal-network
    
  university.api:
    container_name: University.API
    image: university.api
    build:
      context: .
      dockerfile: University.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
    ports:
      - "7065:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - api-network
      - internal-network
    restart: unless-stopped
    
volumes:
  pg_data:

networks:
  internal-network:
    internal: true
  api-network:
    driver: bridge