services:
  university.api:
    image: university.api
    build:
      context: .
      dockerfile: University.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:7065;
      - ASPNETCORE_HTTPS_PORT=7065
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "7065:7065"
    volumes:
        - ~/.aspnet/https:/https:ro